services:
  - type: web
    name: petty-cash-monitoring
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: Petty Cash Monitoring
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://petty-cash-monitoring.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-young-glade-axdohfcg-pooler.c-4.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_V5dfBkoQAPp1
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
